### ISSUE TITLE
Breaks on No Tag DB

### ISSUE THREAD

**Issue by nicholasurban** [kevinjalbert/alfred-notion#1]
I do not use a global tags DB. Therefore none of the commands work.

**Comment by kevinjalbert** [comment]
Hello @nicholasurban,

I appreciate your interest in this project. Unfortunately, this is a non-issue as the Tag DB is a _required_ piece of the solution that this package aims to solve. The fact that none of the commands work is an expected behaviour given your situation.

As a reminder stated in the README:

> A tailored Alfred Workflow that performs tasks using notion-py within the context of a specific Notion Template as described in this blog post.

As well as on the blog post that introduced this repository:

> I like to remind everyone that this is my tailored solution on how I’ve integrated Notion to fit my needs. If you want to use my solution as inspiration or as a foundation, everything is open sourced.

-----

If you want to remove the Tag DB, you are free to fork and make the required modifications to fit your needs.
